spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:hearhere-db.cekgu3hq9fkt.ap-northeast-2.rds.amazonaws.com/?????? ???hearhere-db
    username: admin
    password: tnsdnjs5913!


app:
  localStorePath: ${LOCAL_STORE_PATH}
  nftStorageToken: ${NFT_STORAGE_TOKEN}
  nftAuthorizationKey: ${NFT_AUTHORIZATION_KEY}

  auth:
    accessTokenSecret: ${ACCESS_TOKEN_SECRET}
    refreshTokenSecret: ${REFRESH_TOKEN_SECRET}
    accessTokenExpiry: 86400000
    refreshTokenExpiry: 604800000
    refreshTokenNearExpiryCriterion: 259200000 //갱신 여부 기준 시간, 밀리초 단위임(3일)

#jpa:
#database: mysql
#database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#generate-ddl: true
#hibernate:
#ddl-auto: update
#show_sql: true
#format_sql: true




